### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by master7720** [gerald0mc/Notorious#1]

**Comment by master7720** [comment]
* What went wrong:
Task 'setupdecompworkspace' not found in root project 'notorious'.

**Comment by Tr0llMode** [comment]
same
fix that please

**Comment by Gav06** [comment]
there is no setupDecompWorkspace because it uses a newer version of forgeGradle that doesn't have that

**Comment by JohnShiozo** [comment]
./gradlew build
