### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by Tr0llMode** [gerald0mc/Notorious#2]
not buildable, please fix

**Comment by Tr0llMode** [comment]
wtf how do u builded this

**Comment by Tr0llMode** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/88204047/135473190-cc4cfd96-c40c-4f5c-8da8-c0d1e24812e9.png)

**Comment by ghost** [comment]
brain issue cope

**Comment by gerald0mc** [comment]
> brain issue cope

on g
