### ISSUE TITLE
ratt!!!!

### ISSUE THREAD

**Issue by ghost** [gerald0mc/Notorious#6]
dont download my computer explode

**Comment by K1llb0t** [comment]
Where IS da RAT? Also Notorius on top!

**Comment by master7720** [comment]
> dont download my computer explode

shut up fan

**Comment by ghost** [comment]
Yah ports 5411-5990 are connected to mvncentral.net smh gerald

**Comment by K1llb0t** [comment]
> Yah ports 5411-5990 are connected to mvncentral.net smh gerald

Cry about it😭

**Comment by h4ince** [comment]
just clean it dumb fuck

**Comment by h4ince** [comment]
just clean it dumb fuck

**Comment by gerald0mc** [comment]
bruh its not a rat lmao cant believe i have to say this on a client that is like 2 months old

**Comment by master7720** [comment]
> bruh its not a rat lmao cant believe i have to say this on a client that is like 2 months old

fr its sad

**Comment by K1llb0t** [comment]
client isnt ratted at all...for all monkeys just look into src..and most of u are just joking :trollface:

**Comment by master7720** [comment]
GUYS THE SRC IS NOT OPEN SOURCE !!@!!!!!@

**Comment by gerald0mc** [comment]
> client isnt ratted at all...for all monkeys just look into src..and most of u are just joking :trollface: 

Fr
